# https://travis-ci.org/HearthSim/deck-code-bot
language: python

python: "3.6"

cache: pip

env:
  - TOXENV=py36
  - TOXENV=flake8

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox

script:
  - tox
